version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es_local
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic_stack

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana_local
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    networks:
      - elastic_stack
      
  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      container_name: redis-local
volumes:
  es_data:

networks:
  elastic_stack:
    driver: bridge
